// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: relayer/provers/lcp/shfu_service.proto

package shfu_grpc

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Height represents IBC height with revision number and revision height
type Height struct {
	RevisionNumber uint64 `protobuf:"varint,1,opt,name=revision_number,json=revisionNumber,proto3" json:"revision_number,omitempty"`
	RevisionHeight uint64 `protobuf:"varint,2,opt,name=revision_height,json=revisionHeight,proto3" json:"revision_height,omitempty"`
}

func (m *Height) Reset()         { *m = Height{} }
func (m *Height) String() string { return proto.CompactTextString(m) }
func (*Height) ProtoMessage()    {}
func (*Height) Descriptor() ([]byte, []int) {
	return fileDescriptor_37abe7f9a71f71d3, []int{0}
}
func (m *Height) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Height) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Height.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Height) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Height.Merge(m, src)
}
func (m *Height) XXX_Size() int {
	return m.Size()
}
func (m *Height) XXX_DiscardUnknown() {
	xxx_messageInfo_Height.DiscardUnknown(m)
}

var xxx_messageInfo_Height proto.InternalMessageInfo

// UpdateClientResult represents the result of updateClient operation
type UpdateClientResult struct {
	Message   []byte `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Signature []byte `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (m *UpdateClientResult) Reset()         { *m = UpdateClientResult{} }
func (m *UpdateClientResult) String() string { return proto.CompactTextString(m) }
func (*UpdateClientResult) ProtoMessage()    {}
func (*UpdateClientResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_37abe7f9a71f71d3, []int{1}
}
func (m *UpdateClientResult) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *UpdateClientResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_UpdateClientResult.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *UpdateClientResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateClientResult.Merge(m, src)
}
func (m *UpdateClientResult) XXX_Size() int {
	return m.Size()
}
func (m *UpdateClientResult) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateClientResult.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateClientResult proto.InternalMessageInfo

// SHFURecord represents a SetupHeadersForUpdate record
type SHFURecord struct {
	ChainId             string                `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	CounterpartyChainId string                `protobuf:"bytes,2,opt,name=counterparty_chain_id,json=counterpartyChainId,proto3" json:"counterparty_chain_id,omitempty"`
	FromHeight          *Height               `protobuf:"bytes,3,opt,name=from_height,json=fromHeight,proto3" json:"from_height,omitempty"`
	ToHeight            *Height               `protobuf:"bytes,4,opt,name=to_height,json=toHeight,proto3" json:"to_height,omitempty"`
	ToHeightTime        time.Time             `protobuf:"bytes,5,opt,name=to_height_time,json=toHeightTime,proto3,stdtime" json:"to_height_time"`
	UpdatedAt           time.Time             `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3,stdtime" json:"updated_at"`
	UpdateClientResults []*UpdateClientResult `protobuf:"bytes,7,rep,name=update_client_results,json=updateClientResults,proto3" json:"update_client_results,omitempty"`
	// This contains the Header that was used as latestFinalizedHeader in setupHeadersForUpdate
	LatestFinalizedHeader []byte `protobuf:"bytes,8,opt,name=latest_finalized_header,json=latestFinalizedHeader,proto3" json:"latest_finalized_header,omitempty"`
}

func (m *SHFURecord) Reset()         { *m = SHFURecord{} }
func (m *SHFURecord) String() string { return proto.CompactTextString(m) }
func (*SHFURecord) ProtoMessage()    {}
func (*SHFURecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_37abe7f9a71f71d3, []int{2}
}
func (m *SHFURecord) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SHFURecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SHFURecord.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SHFURecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SHFURecord.Merge(m, src)
}
func (m *SHFURecord) XXX_Size() int {
	return m.Size()
}
func (m *SHFURecord) XXX_DiscardUnknown() {
	xxx_messageInfo_SHFURecord.DiscardUnknown(m)
}

var xxx_messageInfo_SHFURecord proto.InternalMessageInfo

// GetLatestSHFURequest represents a request to get the latest SHFU record for a chain
type GetLatestSHFURequest struct {
	ChainId             string `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	CounterpartyChainId string `protobuf:"bytes,2,opt,name=counterparty_chain_id,json=counterpartyChainId,proto3" json:"counterparty_chain_id,omitempty"`
	RequestId           string `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
}

func (m *GetLatestSHFURequest) Reset()         { *m = GetLatestSHFURequest{} }
func (m *GetLatestSHFURequest) String() string { return proto.CompactTextString(m) }
func (*GetLatestSHFURequest) ProtoMessage()    {}
func (*GetLatestSHFURequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_37abe7f9a71f71d3, []int{3}
}
func (m *GetLatestSHFURequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetLatestSHFURequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetLatestSHFURequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetLatestSHFURequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLatestSHFURequest.Merge(m, src)
}
func (m *GetLatestSHFURequest) XXX_Size() int {
	return m.Size()
}
func (m *GetLatestSHFURequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLatestSHFURequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetLatestSHFURequest proto.InternalMessageInfo

// GetLatestSHFUResponse represents a response containing the latest SHFU record
type GetLatestSHFUResponse struct {
	Record *SHFURecord `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	Found  bool        `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
}

func (m *GetLatestSHFUResponse) Reset()         { *m = GetLatestSHFUResponse{} }
func (m *GetLatestSHFUResponse) String() string { return proto.CompactTextString(m) }
func (*GetLatestSHFUResponse) ProtoMessage()    {}
func (*GetLatestSHFUResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_37abe7f9a71f71d3, []int{4}
}
func (m *GetLatestSHFUResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetLatestSHFUResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetLatestSHFUResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetLatestSHFUResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLatestSHFUResponse.Merge(m, src)
}
func (m *GetLatestSHFUResponse) XXX_Size() int {
	return m.Size()
}
func (m *GetLatestSHFUResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLatestSHFUResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetLatestSHFUResponse proto.InternalMessageInfo

// GetSequentialSHFURecordsRequest represents a request to get sequential SHFU records from a starting height
type GetSequentialSHFURecordsRequest struct {
	ChainId             string  `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	CounterpartyChainId string  `protobuf:"bytes,2,opt,name=counterparty_chain_id,json=counterpartyChainId,proto3" json:"counterparty_chain_id,omitempty"`
	FromHeight          *Height `protobuf:"bytes,3,opt,name=from_height,json=fromHeight,proto3" json:"from_height,omitempty"`
	ToHeight            *Height `protobuf:"bytes,4,opt,name=to_height,json=toHeight,proto3" json:"to_height,omitempty"`
	RequestId           string  `protobuf:"bytes,5,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
}

func (m *GetSequentialSHFURecordsRequest) Reset()         { *m = GetSequentialSHFURecordsRequest{} }
func (m *GetSequentialSHFURecordsRequest) String() string { return proto.CompactTextString(m) }
func (*GetSequentialSHFURecordsRequest) ProtoMessage()    {}
func (*GetSequentialSHFURecordsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_37abe7f9a71f71d3, []int{5}
}
func (m *GetSequentialSHFURecordsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetSequentialSHFURecordsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetSequentialSHFURecordsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetSequentialSHFURecordsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSequentialSHFURecordsRequest.Merge(m, src)
}
func (m *GetSequentialSHFURecordsRequest) XXX_Size() int {
	return m.Size()
}
func (m *GetSequentialSHFURecordsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSequentialSHFURecordsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSequentialSHFURecordsRequest proto.InternalMessageInfo

// GetSequentialSHFURecordsResponse represents a response containing sequential SHFU records
type GetSequentialSHFURecordsResponse struct {
	Records      []*SHFURecord `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	RecordsCount int32         `protobuf:"varint,2,opt,name=records_count,json=recordsCount,proto3" json:"records_count,omitempty"`
}

func (m *GetSequentialSHFURecordsResponse) Reset()         { *m = GetSequentialSHFURecordsResponse{} }
func (m *GetSequentialSHFURecordsResponse) String() string { return proto.CompactTextString(m) }
func (*GetSequentialSHFURecordsResponse) ProtoMessage()    {}
func (*GetSequentialSHFURecordsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_37abe7f9a71f71d3, []int{6}
}
func (m *GetSequentialSHFURecordsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetSequentialSHFURecordsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetSequentialSHFURecordsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetSequentialSHFURecordsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSequentialSHFURecordsResponse.Merge(m, src)
}
func (m *GetSequentialSHFURecordsResponse) XXX_Size() int {
	return m.Size()
}
func (m *GetSequentialSHFURecordsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSequentialSHFURecordsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetSequentialSHFURecordsResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Height)(nil), "relayer.provers.lcp.Height")
	proto.RegisterType((*UpdateClientResult)(nil), "relayer.provers.lcp.UpdateClientResult")
	proto.RegisterType((*SHFURecord)(nil), "relayer.provers.lcp.SHFURecord")
	proto.RegisterType((*GetLatestSHFURequest)(nil), "relayer.provers.lcp.GetLatestSHFURequest")
	proto.RegisterType((*GetLatestSHFUResponse)(nil), "relayer.provers.lcp.GetLatestSHFUResponse")
	proto.RegisterType((*GetSequentialSHFURecordsRequest)(nil), "relayer.provers.lcp.GetSequentialSHFURecordsRequest")
	proto.RegisterType((*GetSequentialSHFURecordsResponse)(nil), "relayer.provers.lcp.GetSequentialSHFURecordsResponse")
}

func init() {
	proto.RegisterFile("relayer/provers/lcp/shfu_service.proto", fileDescriptor_37abe7f9a71f71d3)
}

var fileDescriptor_37abe7f9a71f71d3 = []byte{
	// 700 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x55, 0x4b, 0x6f, 0xd3, 0x4a,
	0x14, 0x8e, 0x9b, 0xe6, 0x75, 0x92, 0xf6, 0x4a, 0xd3, 0x46, 0xd7, 0x37, 0x17, 0x92, 0x28, 0x48,
	0xb4, 0x20, 0x61, 0x4b, 0xe1, 0x2d, 0xb1, 0xa1, 0x91, 0xfa, 0x40, 0x15, 0x0b, 0x97, 0x6e, 0xca,
	0xc2, 0x9a, 0xd8, 0x63, 0xc7, 0x92, 0xe3, 0x31, 0x33, 0xe3, 0x4a, 0x65, 0x89, 0x90, 0xba, 0xed,
	0xcf, 0xea, 0xb2, 0x4b, 0x56, 0x3c, 0xda, 0x5f, 0xc1, 0x0a, 0xe4, 0x19, 0xbb, 0x25, 0x6d, 0x4a,
	0xa9, 0x04, 0x62, 0xe7, 0x73, 0xce, 0xf7, 0x9d, 0x99, 0xf3, 0x9d, 0x4f, 0x1e, 0xb8, 0xcd, 0x48,
	0x88, 0xf7, 0x08, 0x33, 0x63, 0x46, 0x77, 0x09, 0xe3, 0x66, 0xe8, 0xc4, 0x26, 0x1f, 0x79, 0x89,
	0xcd, 0x09, 0xdb, 0x0d, 0x1c, 0x62, 0xc4, 0x8c, 0x0a, 0x8a, 0x16, 0x32, 0x9c, 0x91, 0xe1, 0x8c,
	0xd0, 0x89, 0x5b, 0x8b, 0x3e, 0xf5, 0xa9, 0xac, 0x9b, 0xe9, 0x97, 0x82, 0xb6, 0x3a, 0x3e, 0xa5,
	0x7e, 0x48, 0x4c, 0x19, 0x0d, 0x13, 0xcf, 0x14, 0xc1, 0x98, 0x70, 0x81, 0xc7, 0xb1, 0x02, 0xf4,
	0x76, 0xa0, 0xbc, 0x4e, 0x02, 0x7f, 0x24, 0xd0, 0x12, 0xfc, 0xc3, 0xc8, 0x6e, 0xc0, 0x03, 0x1a,
	0xd9, 0x51, 0x32, 0x1e, 0x12, 0xa6, 0x6b, 0x5d, 0x6d, 0x79, 0xd6, 0x9a, 0xcf, 0xd3, 0x2f, 0x65,
	0x76, 0x02, 0x38, 0x92, 0x5c, 0x7d, 0x66, 0x12, 0xa8, 0x3a, 0xf6, 0x36, 0x01, 0x6d, 0xc7, 0x2e,
	0x16, 0x64, 0x10, 0x06, 0x24, 0x12, 0x16, 0xe1, 0x49, 0x28, 0x90, 0x0e, 0x95, 0x31, 0xe1, 0x1c,
	0xfb, 0x44, 0xf6, 0x6f, 0x58, 0x79, 0x88, 0x6e, 0x40, 0x8d, 0x07, 0x7e, 0x84, 0x45, 0xc2, 0x88,
	0x6c, 0xd9, 0xb0, 0xce, 0x12, 0xbd, 0xaf, 0x45, 0x80, 0xad, 0xf5, 0xd5, 0x6d, 0x8b, 0x38, 0x94,
	0xb9, 0xe8, 0x3f, 0xa8, 0x3a, 0x23, 0x1c, 0x44, 0x76, 0xe0, 0xca, 0x3e, 0x35, 0xab, 0x22, 0xe3,
	0x0d, 0x17, 0xf5, 0xa1, 0xe9, 0xd0, 0x24, 0x12, 0x84, 0xc5, 0x98, 0x89, 0x3d, 0xfb, 0x14, 0x37,
	0x23, 0x71, 0x0b, 0x3f, 0x16, 0x07, 0x19, 0xe7, 0x19, 0xd4, 0x3d, 0x46, 0xc7, 0xf9, 0x40, 0xc5,
	0xae, 0xb6, 0x5c, 0xef, 0xff, 0x6f, 0x4c, 0x51, 0xda, 0x50, 0xd3, 0x59, 0x90, 0xe2, 0x33, 0xed,
	0x9e, 0x40, 0x4d, 0xd0, 0x9c, 0x3b, 0x7b, 0x35, 0xb7, 0x2a, 0x68, 0xc6, 0x7c, 0x01, 0xf3, 0xa7,
	0x4c, 0x3b, 0x5d, 0x8e, 0x5e, 0x92, 0xf4, 0x96, 0xa1, 0x36, 0x67, 0xe4, 0x9b, 0x33, 0x5e, 0xe5,
	0x9b, 0x5b, 0xa9, 0x1e, 0x7e, 0xec, 0x14, 0x0e, 0x3e, 0x75, 0x34, 0xab, 0x91, 0xf7, 0x49, 0x8b,
	0x68, 0x00, 0x90, 0x48, 0xbd, 0x5d, 0x1b, 0x0b, 0xbd, 0x7c, 0x8d, 0x3e, 0xb5, 0x8c, 0xf7, 0x5c,
	0xa0, 0xd7, 0xd0, 0x54, 0x81, 0xed, 0xc8, 0xad, 0xd9, 0x4c, 0xae, 0x8d, 0xeb, 0x95, 0x6e, 0x71,
	0xb9, 0xde, 0x5f, 0x9a, 0x3a, 0xd6, 0xc5, 0x35, 0x5b, 0x0b, 0xc9, 0x85, 0x1c, 0x47, 0x8f, 0xe0,
	0xdf, 0x10, 0x0b, 0xc2, 0x85, 0xed, 0x05, 0x11, 0x0e, 0x83, 0xb7, 0xc4, 0xb5, 0x47, 0x04, 0xbb,
	0x84, 0xe9, 0x55, 0xb9, 0xef, 0xa6, 0x2a, 0xaf, 0xe6, 0xd5, 0x75, 0x59, 0xec, 0xbd, 0xd7, 0x60,
	0x71, 0x8d, 0x88, 0x4d, 0x59, 0x54, 0x26, 0x78, 0x93, 0x10, 0x2e, 0x7e, 0xb7, 0x0b, 0x6e, 0x02,
	0x30, 0xd5, 0x39, 0x05, 0x16, 0x25, 0xb0, 0x96, 0x65, 0x36, 0xdc, 0x9e, 0x07, 0xcd, 0x73, 0xb7,
	0xe0, 0x31, 0x8d, 0x38, 0x41, 0x8f, 0xa1, 0xcc, 0xa4, 0x2d, 0xe5, 0x25, 0xea, 0xfd, 0xce, 0x54,
	0x95, 0xce, 0xdc, 0x6b, 0x65, 0x70, 0xb4, 0x08, 0x25, 0x8f, 0x26, 0x91, 0xba, 0x54, 0xd5, 0x52,
	0x41, 0x6f, 0x7f, 0x06, 0x3a, 0x6b, 0x44, 0x6c, 0xa5, 0x07, 0x47, 0x22, 0xc0, 0xe1, 0x19, 0x93,
	0xff, 0xa1, 0xc9, 0xff, 0x96, 0xff, 0x27, 0x15, 0x2f, 0x9d, 0x57, 0xfc, 0x9d, 0x06, 0xdd, 0xcb,
	0x95, 0xc8, 0xd4, 0x7f, 0x0a, 0x15, 0x25, 0x27, 0xd7, 0x35, 0x69, 0xd2, 0x2b, 0xe5, 0xcf, 0xf1,
	0xe8, 0x16, 0xcc, 0x65, 0x9f, 0xb6, 0x54, 0x45, 0x4a, 0x54, 0xb2, 0x1a, 0x59, 0x72, 0x90, 0xe6,
	0xfa, 0xdf, 0x34, 0xa8, 0xa7, 0xe4, 0x2d, 0xf5, 0x17, 0x46, 0x1e, 0xcc, 0x4d, 0xd8, 0x00, 0xdd,
	0x99, 0x7a, 0xde, 0x34, 0xc3, 0xb6, 0xee, 0xfe, 0x0a, 0x34, 0x9b, 0x6b, 0x5f, 0x03, 0xfd, 0xb2,
	0xe1, 0xd1, 0x83, 0xcb, 0x1a, 0xfd, 0xcc, 0x35, 0xad, 0x87, 0xd7, 0x64, 0xa9, 0x9b, 0xac, 0x6c,
	0x1e, 0x7e, 0x69, 0x17, 0x0e, 0x8f, 0xdb, 0xda, 0xd1, 0x71, 0x5b, 0xfb, 0x7c, 0xdc, 0xd6, 0x0e,
	0x4e, 0xda, 0x85, 0xa3, 0x93, 0x76, 0xe1, 0xc3, 0x49, 0xbb, 0xb0, 0x63, 0xf8, 0x81, 0x18, 0x25,
	0x43, 0xc3, 0xa1, 0x63, 0xd3, 0xc5, 0x02, 0x4b, 0xbf, 0x85, 0x78, 0x98, 0xbe, 0x5f, 0xf7, 0x7c,
	0x6a, 0xca, 0x23, 0xd5, 0x43, 0xe6, 0xb3, 0xd8, 0x19, 0x96, 0xe5, 0xbf, 0xe8, 0xfe, 0xf7, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x3e, 0x90, 0xe6, 0xc7, 0xf0, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SHFUServiceClient is the client API for SHFUService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SHFUServiceClient interface {
	// GetLatestSequentialSHFU retrieves the last SHFU record for a specific chain
	GetLatestSHFU(ctx context.Context, in *GetLatestSHFURequest, opts ...grpc.CallOption) (*GetLatestSHFUResponse, error)
	// GetSequentialSHFURecords retrieves sequential SHFU records starting from the specified height
	// Returns records in chronological order where each record's FromHeight matches the previous record's ToHeight
	GetSequentialSHFURecords(ctx context.Context, in *GetSequentialSHFURecordsRequest, opts ...grpc.CallOption) (*GetSequentialSHFURecordsResponse, error)
}

type sHFUServiceClient struct {
	cc grpc1.ClientConn
}

func NewSHFUServiceClient(cc grpc1.ClientConn) SHFUServiceClient {
	return &sHFUServiceClient{cc}
}

func (c *sHFUServiceClient) GetLatestSHFU(ctx context.Context, in *GetLatestSHFURequest, opts ...grpc.CallOption) (*GetLatestSHFUResponse, error) {
	out := new(GetLatestSHFUResponse)
	err := c.cc.Invoke(ctx, "/relayer.provers.lcp.SHFUService/GetLatestSHFU", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sHFUServiceClient) GetSequentialSHFURecords(ctx context.Context, in *GetSequentialSHFURecordsRequest, opts ...grpc.CallOption) (*GetSequentialSHFURecordsResponse, error) {
	out := new(GetSequentialSHFURecordsResponse)
	err := c.cc.Invoke(ctx, "/relayer.provers.lcp.SHFUService/GetSequentialSHFURecords", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SHFUServiceServer is the server API for SHFUService service.
type SHFUServiceServer interface {
	// GetLatestSequentialSHFU retrieves the last SHFU record for a specific chain
	GetLatestSHFU(context.Context, *GetLatestSHFURequest) (*GetLatestSHFUResponse, error)
	// GetSequentialSHFURecords retrieves sequential SHFU records starting from the specified height
	// Returns records in chronological order where each record's FromHeight matches the previous record's ToHeight
	GetSequentialSHFURecords(context.Context, *GetSequentialSHFURecordsRequest) (*GetSequentialSHFURecordsResponse, error)
}

// UnimplementedSHFUServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSHFUServiceServer struct {
}

func (*UnimplementedSHFUServiceServer) GetLatestSHFU(ctx context.Context, req *GetLatestSHFURequest) (*GetLatestSHFUResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLatestSHFU not implemented")
}
func (*UnimplementedSHFUServiceServer) GetSequentialSHFURecords(ctx context.Context, req *GetSequentialSHFURecordsRequest) (*GetSequentialSHFURecordsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSequentialSHFURecords not implemented")
}

func RegisterSHFUServiceServer(s grpc1.Server, srv SHFUServiceServer) {
	s.RegisterService(&_SHFUService_serviceDesc, srv)
}

func _SHFUService_GetLatestSHFU_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLatestSHFURequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SHFUServiceServer).GetLatestSHFU(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/relayer.provers.lcp.SHFUService/GetLatestSHFU",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SHFUServiceServer).GetLatestSHFU(ctx, req.(*GetLatestSHFURequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SHFUService_GetSequentialSHFURecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSequentialSHFURecordsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SHFUServiceServer).GetSequentialSHFURecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/relayer.provers.lcp.SHFUService/GetSequentialSHFURecords",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SHFUServiceServer).GetSequentialSHFURecords(ctx, req.(*GetSequentialSHFURecordsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SHFUService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "relayer.provers.lcp.SHFUService",
	HandlerType: (*SHFUServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLatestSHFU",
			Handler:    _SHFUService_GetLatestSHFU_Handler,
		},
		{
			MethodName: "GetSequentialSHFURecords",
			Handler:    _SHFUService_GetSequentialSHFURecords_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "relayer/provers/lcp/shfu_service.proto",
}

func (m *Height) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Height) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Height) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.RevisionHeight != 0 {
		i = encodeVarintShfuService(dAtA, i, uint64(m.RevisionHeight))
		i--
		dAtA[i] = 0x10
	}
	if m.RevisionNumber != 0 {
		i = encodeVarintShfuService(dAtA, i, uint64(m.RevisionNumber))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *UpdateClientResult) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UpdateClientResult) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *UpdateClientResult) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Signature) > 0 {
		i -= len(m.Signature)
		copy(dAtA[i:], m.Signature)
		i = encodeVarintShfuService(dAtA, i, uint64(len(m.Signature)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Message) > 0 {
		i -= len(m.Message)
		copy(dAtA[i:], m.Message)
		i = encodeVarintShfuService(dAtA, i, uint64(len(m.Message)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *SHFURecord) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SHFURecord) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SHFURecord) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.LatestFinalizedHeader) > 0 {
		i -= len(m.LatestFinalizedHeader)
		copy(dAtA[i:], m.LatestFinalizedHeader)
		i = encodeVarintShfuService(dAtA, i, uint64(len(m.LatestFinalizedHeader)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.UpdateClientResults) > 0 {
		for iNdEx := len(m.UpdateClientResults) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.UpdateClientResults[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintShfuService(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x3a
		}
	}
	n1, err1 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.UpdatedAt, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.UpdatedAt):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintShfuService(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x32
	n2, err2 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.ToHeightTime, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.ToHeightTime):])
	if err2 != nil {
		return 0, err2
	}
	i -= n2
	i = encodeVarintShfuService(dAtA, i, uint64(n2))
	i--
	dAtA[i] = 0x2a
	if m.ToHeight != nil {
		{
			size, err := m.ToHeight.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintShfuService(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if m.FromHeight != nil {
		{
			size, err := m.FromHeight.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintShfuService(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if len(m.CounterpartyChainId) > 0 {
		i -= len(m.CounterpartyChainId)
		copy(dAtA[i:], m.CounterpartyChainId)
		i = encodeVarintShfuService(dAtA, i, uint64(len(m.CounterpartyChainId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ChainId) > 0 {
		i -= len(m.ChainId)
		copy(dAtA[i:], m.ChainId)
		i = encodeVarintShfuService(dAtA, i, uint64(len(m.ChainId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GetLatestSHFURequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetLatestSHFURequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetLatestSHFURequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.RequestId) > 0 {
		i -= len(m.RequestId)
		copy(dAtA[i:], m.RequestId)
		i = encodeVarintShfuService(dAtA, i, uint64(len(m.RequestId)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.CounterpartyChainId) > 0 {
		i -= len(m.CounterpartyChainId)
		copy(dAtA[i:], m.CounterpartyChainId)
		i = encodeVarintShfuService(dAtA, i, uint64(len(m.CounterpartyChainId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ChainId) > 0 {
		i -= len(m.ChainId)
		copy(dAtA[i:], m.ChainId)
		i = encodeVarintShfuService(dAtA, i, uint64(len(m.ChainId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GetLatestSHFUResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetLatestSHFUResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetLatestSHFUResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Found {
		i--
		if m.Found {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	if m.Record != nil {
		{
			size, err := m.Record.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintShfuService(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GetSequentialSHFURecordsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetSequentialSHFURecordsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetSequentialSHFURecordsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.RequestId) > 0 {
		i -= len(m.RequestId)
		copy(dAtA[i:], m.RequestId)
		i = encodeVarintShfuService(dAtA, i, uint64(len(m.RequestId)))
		i--
		dAtA[i] = 0x2a
	}
	if m.ToHeight != nil {
		{
			size, err := m.ToHeight.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintShfuService(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if m.FromHeight != nil {
		{
			size, err := m.FromHeight.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintShfuService(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if len(m.CounterpartyChainId) > 0 {
		i -= len(m.CounterpartyChainId)
		copy(dAtA[i:], m.CounterpartyChainId)
		i = encodeVarintShfuService(dAtA, i, uint64(len(m.CounterpartyChainId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ChainId) > 0 {
		i -= len(m.ChainId)
		copy(dAtA[i:], m.ChainId)
		i = encodeVarintShfuService(dAtA, i, uint64(len(m.ChainId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GetSequentialSHFURecordsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetSequentialSHFURecordsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetSequentialSHFURecordsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.RecordsCount != 0 {
		i = encodeVarintShfuService(dAtA, i, uint64(m.RecordsCount))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Records) > 0 {
		for iNdEx := len(m.Records) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Records[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintShfuService(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintShfuService(dAtA []byte, offset int, v uint64) int {
	offset -= sovShfuService(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Height) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.RevisionNumber != 0 {
		n += 1 + sovShfuService(uint64(m.RevisionNumber))
	}
	if m.RevisionHeight != 0 {
		n += 1 + sovShfuService(uint64(m.RevisionHeight))
	}
	return n
}

func (m *UpdateClientResult) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Message)
	if l > 0 {
		n += 1 + l + sovShfuService(uint64(l))
	}
	l = len(m.Signature)
	if l > 0 {
		n += 1 + l + sovShfuService(uint64(l))
	}
	return n
}

func (m *SHFURecord) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ChainId)
	if l > 0 {
		n += 1 + l + sovShfuService(uint64(l))
	}
	l = len(m.CounterpartyChainId)
	if l > 0 {
		n += 1 + l + sovShfuService(uint64(l))
	}
	if m.FromHeight != nil {
		l = m.FromHeight.Size()
		n += 1 + l + sovShfuService(uint64(l))
	}
	if m.ToHeight != nil {
		l = m.ToHeight.Size()
		n += 1 + l + sovShfuService(uint64(l))
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.ToHeightTime)
	n += 1 + l + sovShfuService(uint64(l))
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.UpdatedAt)
	n += 1 + l + sovShfuService(uint64(l))
	if len(m.UpdateClientResults) > 0 {
		for _, e := range m.UpdateClientResults {
			l = e.Size()
			n += 1 + l + sovShfuService(uint64(l))
		}
	}
	l = len(m.LatestFinalizedHeader)
	if l > 0 {
		n += 1 + l + sovShfuService(uint64(l))
	}
	return n
}

func (m *GetLatestSHFURequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ChainId)
	if l > 0 {
		n += 1 + l + sovShfuService(uint64(l))
	}
	l = len(m.CounterpartyChainId)
	if l > 0 {
		n += 1 + l + sovShfuService(uint64(l))
	}
	l = len(m.RequestId)
	if l > 0 {
		n += 1 + l + sovShfuService(uint64(l))
	}
	return n
}

func (m *GetLatestSHFUResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Record != nil {
		l = m.Record.Size()
		n += 1 + l + sovShfuService(uint64(l))
	}
	if m.Found {
		n += 2
	}
	return n
}

func (m *GetSequentialSHFURecordsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ChainId)
	if l > 0 {
		n += 1 + l + sovShfuService(uint64(l))
	}
	l = len(m.CounterpartyChainId)
	if l > 0 {
		n += 1 + l + sovShfuService(uint64(l))
	}
	if m.FromHeight != nil {
		l = m.FromHeight.Size()
		n += 1 + l + sovShfuService(uint64(l))
	}
	if m.ToHeight != nil {
		l = m.ToHeight.Size()
		n += 1 + l + sovShfuService(uint64(l))
	}
	l = len(m.RequestId)
	if l > 0 {
		n += 1 + l + sovShfuService(uint64(l))
	}
	return n
}

func (m *GetSequentialSHFURecordsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Records) > 0 {
		for _, e := range m.Records {
			l = e.Size()
			n += 1 + l + sovShfuService(uint64(l))
		}
	}
	if m.RecordsCount != 0 {
		n += 1 + sovShfuService(uint64(m.RecordsCount))
	}
	return n
}

func sovShfuService(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozShfuService(x uint64) (n int) {
	return sovShfuService(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Height) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowShfuService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Height: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Height: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RevisionNumber", wireType)
			}
			m.RevisionNumber = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowShfuService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RevisionNumber |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RevisionHeight", wireType)
			}
			m.RevisionHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowShfuService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RevisionHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipShfuService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthShfuService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *UpdateClientResult) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowShfuService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UpdateClientResult: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UpdateClientResult: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Message", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowShfuService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthShfuService
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthShfuService
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Message = append(m.Message[:0], dAtA[iNdEx:postIndex]...)
			if m.Message == nil {
				m.Message = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signature", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowShfuService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthShfuService
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthShfuService
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signature = append(m.Signature[:0], dAtA[iNdEx:postIndex]...)
			if m.Signature == nil {
				m.Signature = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipShfuService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthShfuService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SHFURecord) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowShfuService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SHFURecord: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SHFURecord: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowShfuService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthShfuService
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthShfuService
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChainId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CounterpartyChainId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowShfuService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthShfuService
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthShfuService
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CounterpartyChainId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FromHeight", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowShfuService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthShfuService
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthShfuService
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.FromHeight == nil {
				m.FromHeight = &Height{}
			}
			if err := m.FromHeight.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ToHeight", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowShfuService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthShfuService
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthShfuService
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ToHeight == nil {
				m.ToHeight = &Height{}
			}
			if err := m.ToHeight.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ToHeightTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowShfuService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthShfuService
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthShfuService
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.ToHeightTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdatedAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowShfuService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthShfuService
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthShfuService
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.UpdatedAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdateClientResults", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowShfuService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthShfuService
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthShfuService
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UpdateClientResults = append(m.UpdateClientResults, &UpdateClientResult{})
			if err := m.UpdateClientResults[len(m.UpdateClientResults)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LatestFinalizedHeader", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowShfuService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthShfuService
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthShfuService
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LatestFinalizedHeader = append(m.LatestFinalizedHeader[:0], dAtA[iNdEx:postIndex]...)
			if m.LatestFinalizedHeader == nil {
				m.LatestFinalizedHeader = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipShfuService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthShfuService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetLatestSHFURequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowShfuService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetLatestSHFURequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetLatestSHFURequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowShfuService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthShfuService
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthShfuService
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChainId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CounterpartyChainId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowShfuService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthShfuService
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthShfuService
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CounterpartyChainId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowShfuService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthShfuService
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthShfuService
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RequestId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipShfuService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthShfuService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetLatestSHFUResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowShfuService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetLatestSHFUResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetLatestSHFUResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Record", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowShfuService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthShfuService
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthShfuService
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Record == nil {
				m.Record = &SHFURecord{}
			}
			if err := m.Record.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Found", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowShfuService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Found = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipShfuService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthShfuService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetSequentialSHFURecordsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowShfuService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetSequentialSHFURecordsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetSequentialSHFURecordsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowShfuService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthShfuService
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthShfuService
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChainId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CounterpartyChainId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowShfuService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthShfuService
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthShfuService
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CounterpartyChainId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FromHeight", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowShfuService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthShfuService
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthShfuService
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.FromHeight == nil {
				m.FromHeight = &Height{}
			}
			if err := m.FromHeight.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ToHeight", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowShfuService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthShfuService
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthShfuService
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ToHeight == nil {
				m.ToHeight = &Height{}
			}
			if err := m.ToHeight.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowShfuService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthShfuService
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthShfuService
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RequestId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipShfuService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthShfuService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetSequentialSHFURecordsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowShfuService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetSequentialSHFURecordsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetSequentialSHFURecordsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Records", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowShfuService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthShfuService
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthShfuService
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Records = append(m.Records, &SHFURecord{})
			if err := m.Records[len(m.Records)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RecordsCount", wireType)
			}
			m.RecordsCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowShfuService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RecordsCount |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipShfuService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthShfuService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipShfuService(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowShfuService
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowShfuService
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowShfuService
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthShfuService
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupShfuService
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthShfuService
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthShfuService        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowShfuService          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupShfuService = fmt.Errorf("proto: unexpected end of group")
)
