#!/bin/bash
set -eu

RLY="${RLY_BIN} --debug"

UPDATE_CMD="${RLY} lcp update-operators ibc01"

for IS_SRC in true false; do
  echo "src=${IS_SRC}"
  if [ "${IS_SRC}" = true ]; then
    NEW_OPERATOR=0xcb96F8d6C2d543102184d679D7829b39434E4EEc
  else
    NEW_OPERATOR=0x9722414d09f43fb02235d739B50F4C027F43e657
  fi

  output=$(${UPDATE_CMD} --src=${IS_SRC} --nonce 2 --new_operators ${NEW_OPERATOR} --threshold_denominator 1 --threshold_numerator 1 2>&1 || true)
  if [[ $output == *"invalid nonce"* ]]; then
    echo "01: OK"
  else
    echo "01: Unexpected error message: $output"
    exit 1
  fi

  output=$(${UPDATE_CMD} --src=${IS_SRC} --nonce 1 --new_operators ${NEW_OPERATOR} --threshold_denominator 0 --threshold_numerator 1 2>&1 || true)
  if [[ $output == *"invalid threshold"* ]]; then
    echo "02: OK"
  else
    echo "02: Unexpected error message: $output"
    exit 1
  fi

  output=$(${UPDATE_CMD} --src=${IS_SRC} --nonce 1 --new_operators ${NEW_OPERATOR} --threshold_denominator 1 --threshold_numerator 0 2>&1 || true)
  if [[ $output == *"invalid threshold"* ]]; then
    echo "03: OK"
  else
    echo "03: Unexpected error message: $output"
    exit 1
  fi

  output=$(${UPDATE_CMD} --src=${IS_SRC} --nonce 1 --new_operators ${NEW_OPERATOR} --threshold_denominator 1 --threshold_numerator 2 2>&1 || true)
  if [[ $output == *"new operators threshold numerator cannot be greater than denominator"* ]]; then
    echo "04: OK"
  else
    echo "04: Unexpected error message: $output"
    exit 1
  fi

  # should be successful
  ${UPDATE_CMD} --src=${IS_SRC} --nonce 1 --new_operators ${NEW_OPERATOR} --threshold_denominator 1 --threshold_numerator 1
  echo "05: OK"
  ${UPDATE_CMD} --src=${IS_SRC} --nonce 2 --new_operators ${NEW_OPERATOR} --threshold_denominator 1 --threshold_numerator 1
  echo "06: OK"
done
