#!/bin/bash

set -eu

RLY="${RLY_BIN} --debug"

src_elc_client_id=$(${RLY} lcp create-elc ibc01 --src | jq -r '.elc_client_id')
dst_elc_client_id=$(${RLY} lcp create-elc ibc01 --src=false | jq -r '.elc_client_id')

echo "src: ELC client id: ${src_elc_client_id}"
echo "dst: ELC client id: ${dst_elc_client_id}"

echo "sleeping for 5 seconds"
sleep 5

${RLY} lcp update-elc ibc01 --src --elc_client_id=${src_elc_client_id}
${RLY} lcp update-elc ibc01 --src=false --elc_client_id=${dst_elc_client_id}
