// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: relayer/provers/lcp/config/config.proto

package relay

import (
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/codec/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ProverConfig struct {
	OriginProver *types.Any `protobuf:"bytes,1,opt,name=origin_prover,json=originProver,proto3" json:"origin_prover,omitempty"`
	// hex string
	LcpServiceAddress string `protobuf:"bytes,2,opt,name=lcp_service_address,json=lcpServiceAddress,proto3" json:"lcp_service_address,omitempty"`
	// hex string
	Mrenclave            string   `protobuf:"bytes,3,opt,name=mrenclave,proto3" json:"mrenclave,omitempty"`
	AllowedQuoteStatuses []string `protobuf:"bytes,4,rep,name=allowed_quote_statuses,json=allowedQuoteStatuses,proto3" json:"allowed_quote_statuses,omitempty"`
	AllowedAdvisoryIds   []string `protobuf:"bytes,5,rep,name=allowed_advisory_ids,json=allowedAdvisoryIds,proto3" json:"allowed_advisory_ids,omitempty"`
	// unit: seconds
	KeyExpiration               uint64 `protobuf:"varint,6,opt,name=key_expiration,json=keyExpiration,proto3" json:"key_expiration,omitempty"`
	ElcClientId                 string `protobuf:"bytes,7,opt,name=elc_client_id,json=elcClientId,proto3" json:"elc_client_id,omitempty"`
	MessageAggregation          bool   `protobuf:"varint,8,opt,name=message_aggregation,json=messageAggregation,proto3" json:"message_aggregation,omitempty"`
	MessageAggregationBatchSize uint64 `protobuf:"varint,9,opt,name=message_aggregation_batch_size,json=messageAggregationBatchSize,proto3" json:"message_aggregation_batch_size,omitempty"`
}

func (m *ProverConfig) Reset()         { *m = ProverConfig{} }
func (m *ProverConfig) String() string { return proto.CompactTextString(m) }
func (*ProverConfig) ProtoMessage()    {}
func (*ProverConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e6956e1b8ef896e, []int{0}
}
func (m *ProverConfig) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ProverConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ProverConfig.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ProverConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProverConfig.Merge(m, src)
}
func (m *ProverConfig) XXX_Size() int {
	return m.Size()
}
func (m *ProverConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ProverConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ProverConfig proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ProverConfig)(nil), "relayer.provers.lcp.config.ProverConfig")
}

func init() {
	proto.RegisterFile("relayer/provers/lcp/config/config.proto", fileDescriptor_2e6956e1b8ef896e)
}

var fileDescriptor_2e6956e1b8ef896e = []byte{
	// 439 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0x31, 0x6f, 0x13, 0x31,
	0x1c, 0xc5, 0x73, 0xa4, 0x94, 0xc6, 0x6d, 0x90, 0x70, 0x23, 0x74, 0x04, 0x74, 0x8a, 0x2a, 0x10,
	0xb7, 0x70, 0x46, 0xc0, 0xc2, 0x98, 0x44, 0x0c, 0xdd, 0xe0, 0xb2, 0xb1, 0x58, 0x3e, 0xfb, 0x5f,
	0xc7, 0xaa, 0x73, 0x3e, 0x6c, 0x27, 0x70, 0xfd, 0x14, 0x7c, 0x24, 0xc6, 0x8e, 0x1d, 0x19, 0x21,
	0xf9, 0x22, 0x28, 0xf6, 0x95, 0x0e, 0x30, 0xd9, 0x7e, 0xbf, 0xf7, 0x9e, 0xfe, 0x92, 0xff, 0xe8,
	0xa5, 0x05, 0xcd, 0x5a, 0xb0, 0xa4, 0xb1, 0x66, 0x03, 0xd6, 0x11, 0xcd, 0x1b, 0xc2, 0x4d, 0x7d,
	0xa1, 0x64, 0x77, 0x14, 0x8d, 0x35, 0xde, 0xe0, 0x71, 0x67, 0x2c, 0x3a, 0x63, 0xa1, 0x79, 0x53,
	0x44, 0xc7, 0x78, 0x24, 0x8d, 0x34, 0xc1, 0x46, 0xf6, 0xb7, 0x98, 0x18, 0x3f, 0x91, 0xc6, 0x48,
	0x0d, 0x24, 0xbc, 0xaa, 0xf5, 0x05, 0x61, 0x75, 0x1b, 0xd1, 0xd9, 0x8f, 0x3e, 0x3a, 0xf9, 0x18,
	0x7a, 0xe6, 0xa1, 0x01, 0xbf, 0x47, 0x43, 0x63, 0x95, 0x54, 0x35, 0x8d, 0xf5, 0x69, 0x32, 0x49,
	0xf2, 0xe3, 0x37, 0xa3, 0x22, 0x76, 0x14, 0xb7, 0x1d, 0xc5, 0xb4, 0x6e, 0xcb, 0x93, 0x68, 0x8d,
	0x05, 0xb8, 0x40, 0xa7, 0x9a, 0x37, 0xd4, 0x81, 0xdd, 0x28, 0x0e, 0x94, 0x09, 0x61, 0xc1, 0xb9,
	0xf4, 0xde, 0x24, 0xc9, 0x07, 0xe5, 0x23, 0xcd, 0x9b, 0x45, 0x24, 0xd3, 0x08, 0xf0, 0x33, 0x34,
	0x58, 0x59, 0xa8, 0xb9, 0x66, 0x1b, 0x48, 0xfb, 0xc1, 0x75, 0x27, 0xe0, 0x77, 0xe8, 0x31, 0xd3,
	0xda, 0x7c, 0x05, 0x41, 0xbf, 0xac, 0x8d, 0x07, 0xea, 0x3c, 0xf3, 0x6b, 0x07, 0x2e, 0x3d, 0x98,
	0xf4, 0xf3, 0x41, 0x39, 0xea, 0xe8, 0xa7, 0x3d, 0x5c, 0x74, 0x0c, 0xbf, 0x46, 0xb7, 0x3a, 0x65,
	0x62, 0xa3, 0x9c, 0xb1, 0x2d, 0x55, 0xc2, 0xa5, 0xf7, 0x43, 0x06, 0x77, 0x6c, 0xda, 0xa1, 0x73,
	0xe1, 0xf0, 0x0b, 0xf4, 0xf0, 0x12, 0x5a, 0x0a, 0xdf, 0x1a, 0x65, 0x99, 0x57, 0xa6, 0x4e, 0x0f,
	0x27, 0x49, 0x7e, 0x50, 0x0e, 0x2f, 0xa1, 0xfd, 0xf0, 0x57, 0xc4, 0x67, 0x68, 0x08, 0x9a, 0x53,
	0xae, 0x15, 0xd4, 0x9e, 0x2a, 0x91, 0x3e, 0x08, 0x03, 0x1f, 0x83, 0xe6, 0xf3, 0xa0, 0x9d, 0x0b,
	0x4c, 0xd0, 0xe9, 0x0a, 0x9c, 0x63, 0x12, 0x28, 0x93, 0xd2, 0x82, 0x8c, 0x7d, 0x47, 0x93, 0x24,
	0x3f, 0x2a, 0x71, 0x87, 0xa6, 0x77, 0x04, 0xcf, 0x51, 0xf6, 0x9f, 0x00, 0xad, 0x98, 0xe7, 0x4b,
	0xea, 0xd4, 0x15, 0xa4, 0x83, 0x30, 0xcb, 0xd3, 0x7f, 0xb3, 0xb3, 0xbd, 0x67, 0xa1, 0xae, 0x60,
	0x36, 0xbb, 0xfe, 0x9d, 0xf5, 0xae, 0xb7, 0x59, 0x72, 0xb3, 0xcd, 0x92, 0x5f, 0xdb, 0x2c, 0xf9,
	0xbe, 0xcb, 0x7a, 0x37, 0xbb, 0xac, 0xf7, 0x73, 0x97, 0xf5, 0x3e, 0x3f, 0x97, 0xca, 0x2f, 0xd7,
	0x55, 0xc1, 0xcd, 0x8a, 0x08, 0xe6, 0x19, 0x5f, 0x32, 0x55, 0x6b, 0x56, 0xed, 0xd7, 0xeb, 0x95,
	0x34, 0x24, 0x2c, 0x53, 0x75, 0x18, 0xbe, 0xf5, 0xed, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc1,
	0xc0, 0x72, 0xde, 0x85, 0x02, 0x00, 0x00,
}

func (m *ProverConfig) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ProverConfig) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ProverConfig) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MessageAggregationBatchSize != 0 {
		i = encodeVarintConfig(dAtA, i, uint64(m.MessageAggregationBatchSize))
		i--
		dAtA[i] = 0x48
	}
	if m.MessageAggregation {
		i--
		if m.MessageAggregation {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x40
	}
	if len(m.ElcClientId) > 0 {
		i -= len(m.ElcClientId)
		copy(dAtA[i:], m.ElcClientId)
		i = encodeVarintConfig(dAtA, i, uint64(len(m.ElcClientId)))
		i--
		dAtA[i] = 0x3a
	}
	if m.KeyExpiration != 0 {
		i = encodeVarintConfig(dAtA, i, uint64(m.KeyExpiration))
		i--
		dAtA[i] = 0x30
	}
	if len(m.AllowedAdvisoryIds) > 0 {
		for iNdEx := len(m.AllowedAdvisoryIds) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.AllowedAdvisoryIds[iNdEx])
			copy(dAtA[i:], m.AllowedAdvisoryIds[iNdEx])
			i = encodeVarintConfig(dAtA, i, uint64(len(m.AllowedAdvisoryIds[iNdEx])))
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.AllowedQuoteStatuses) > 0 {
		for iNdEx := len(m.AllowedQuoteStatuses) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.AllowedQuoteStatuses[iNdEx])
			copy(dAtA[i:], m.AllowedQuoteStatuses[iNdEx])
			i = encodeVarintConfig(dAtA, i, uint64(len(m.AllowedQuoteStatuses[iNdEx])))
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.Mrenclave) > 0 {
		i -= len(m.Mrenclave)
		copy(dAtA[i:], m.Mrenclave)
		i = encodeVarintConfig(dAtA, i, uint64(len(m.Mrenclave)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.LcpServiceAddress) > 0 {
		i -= len(m.LcpServiceAddress)
		copy(dAtA[i:], m.LcpServiceAddress)
		i = encodeVarintConfig(dAtA, i, uint64(len(m.LcpServiceAddress)))
		i--
		dAtA[i] = 0x12
	}
	if m.OriginProver != nil {
		{
			size, err := m.OriginProver.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintConfig(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintConfig(dAtA []byte, offset int, v uint64) int {
	offset -= sovConfig(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ProverConfig) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.OriginProver != nil {
		l = m.OriginProver.Size()
		n += 1 + l + sovConfig(uint64(l))
	}
	l = len(m.LcpServiceAddress)
	if l > 0 {
		n += 1 + l + sovConfig(uint64(l))
	}
	l = len(m.Mrenclave)
	if l > 0 {
		n += 1 + l + sovConfig(uint64(l))
	}
	if len(m.AllowedQuoteStatuses) > 0 {
		for _, s := range m.AllowedQuoteStatuses {
			l = len(s)
			n += 1 + l + sovConfig(uint64(l))
		}
	}
	if len(m.AllowedAdvisoryIds) > 0 {
		for _, s := range m.AllowedAdvisoryIds {
			l = len(s)
			n += 1 + l + sovConfig(uint64(l))
		}
	}
	if m.KeyExpiration != 0 {
		n += 1 + sovConfig(uint64(m.KeyExpiration))
	}
	l = len(m.ElcClientId)
	if l > 0 {
		n += 1 + l + sovConfig(uint64(l))
	}
	if m.MessageAggregation {
		n += 2
	}
	if m.MessageAggregationBatchSize != 0 {
		n += 1 + sovConfig(uint64(m.MessageAggregationBatchSize))
	}
	return n
}

func sovConfig(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozConfig(x uint64) (n int) {
	return sovConfig(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ProverConfig) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowConfig
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ProverConfig: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ProverConfig: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OriginProver", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthConfig
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.OriginProver == nil {
				m.OriginProver = &types.Any{}
			}
			if err := m.OriginProver.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LcpServiceAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConfig
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LcpServiceAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Mrenclave", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConfig
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Mrenclave = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AllowedQuoteStatuses", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConfig
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AllowedQuoteStatuses = append(m.AllowedQuoteStatuses, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AllowedAdvisoryIds", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConfig
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AllowedAdvisoryIds = append(m.AllowedAdvisoryIds, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field KeyExpiration", wireType)
			}
			m.KeyExpiration = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.KeyExpiration |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ElcClientId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConfig
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ElcClientId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MessageAggregation", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.MessageAggregation = bool(v != 0)
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MessageAggregationBatchSize", wireType)
			}
			m.MessageAggregationBatchSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MessageAggregationBatchSize |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipConfig(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthConfig
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipConfig(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowConfig
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthConfig
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupConfig
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthConfig
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthConfig        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowConfig          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupConfig = fmt.Errorf("proto: unexpected end of group")
)
