// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: relayer/provers/lcp/config/config.proto

package relay

import (
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/codec/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ProverConfig struct {
	OriginProver *types.Any `protobuf:"bytes,1,opt,name=origin_prover,json=originProver,proto3" json:"origin_prover,omitempty"`
	// hex string
	LcpServiceAddress string `protobuf:"bytes,2,opt,name=lcp_service_address,json=lcpServiceAddress,proto3" json:"lcp_service_address,omitempty"`
	// unit: seconds
	LcpServiceDialTimeout uint64 `protobuf:"varint,3,opt,name=lcp_service_dial_timeout,json=lcpServiceDialTimeout,proto3" json:"lcp_service_dial_timeout,omitempty"`
	// hex string
	Mrenclave            string   `protobuf:"bytes,4,opt,name=mrenclave,proto3" json:"mrenclave,omitempty"`
	AllowedQuoteStatuses []string `protobuf:"bytes,5,rep,name=allowed_quote_statuses,json=allowedQuoteStatuses,proto3" json:"allowed_quote_statuses,omitempty"`
	AllowedAdvisoryIds   []string `protobuf:"bytes,6,rep,name=allowed_advisory_ids,json=allowedAdvisoryIds,proto3" json:"allowed_advisory_ids,omitempty"`
	// unit: seconds
	KeyExpiration uint64 `protobuf:"varint,7,opt,name=key_expiration,json=keyExpiration,proto3" json:"key_expiration,omitempty"`
	// unit: seconds, buffer time before expiration to proactively update the enclave key
	KeyUpdateBufferTime         uint64 `protobuf:"varint,8,opt,name=key_update_buffer_time,json=keyUpdateBufferTime,proto3" json:"key_update_buffer_time,omitempty"`
	ElcClientId                 string `protobuf:"bytes,9,opt,name=elc_client_id,json=elcClientId,proto3" json:"elc_client_id,omitempty"`
	MessageAggregation          bool   `protobuf:"varint,10,opt,name=message_aggregation,json=messageAggregation,proto3" json:"message_aggregation,omitempty"`
	MessageAggregationBatchSize uint64 `protobuf:"varint,11,opt,name=message_aggregation_batch_size,json=messageAggregationBatchSize,proto3" json:"message_aggregation_batch_size,omitempty"`
	IsDebugEnclave              bool   `protobuf:"varint,12,opt,name=is_debug_enclave,json=isDebugEnclave,proto3" json:"is_debug_enclave,omitempty"`
	// --- Operator Config --- //
	// if empty, any operator is allowed (default)
	// otherwise, only operators in this list are allowed
	Operators []string `protobuf:"bytes,13,rep,name=operators,proto3" json:"operators,omitempty"`
	// this only works when operators is not empty
	// the value must be less than or equal to 1
	OperatorsThreshold Fraction `protobuf:"bytes,14,opt,name=operators_threshold,json=operatorsThreshold,proto3" json:"operators_threshold"`
	// signer for eip712 commitment
	OperatorSigner                           *types.Any `protobuf:"bytes,15,opt,name=operator_signer,json=operatorSigner,proto3" json:"operator_signer,omitempty"`
	CurrentTcbEvaluationDataNumber           uint32     `protobuf:"varint,16,opt,name=current_tcb_evaluation_data_number,json=currentTcbEvaluationDataNumber,proto3" json:"current_tcb_evaluation_data_number,omitempty"`
	TcbEvaluationDataNumberUpdateGracePeriod uint32     `protobuf:"varint,17,opt,name=tcb_evaluation_data_number_update_grace_period,json=tcbEvaluationDataNumberUpdateGracePeriod,proto3" json:"tcb_evaluation_data_number_update_grace_period,omitempty"`
	// zkvm config
	//
	// Types that are valid to be assigned to ZkvmConfig:
	//	*ProverConfig_Risc0ZkvmConfig
	ZkvmConfig isProverConfig_ZkvmConfig `protobuf_oneof:"zkvm_config"`
	// eip712 params
	//
	// Types that are valid to be assigned to OperatorsEip712Params:
	//	*ProverConfig_OperatorsEip712EvmChainParams
	//	*ProverConfig_OperatorsEip712CosmosChainParams
	OperatorsEip712Params isProverConfig_OperatorsEip712Params `protobuf_oneof:"operators_eip712_params"`
	// max chunk size(byte) for update client
	MaxChunkSizeForUpdateClient uint32 `protobuf:"varint,33,opt,name=max_chunk_size_for_update_client,json=maxChunkSizeForUpdateClient,proto3" json:"max_chunk_size_for_update_client,omitempty"`
	// SHFU gRPC server address
	// if empty (default), local implementation will be used
	// if specified, SetupHeadersForUpdate will use this gRPC server instead
	ShfuGrpcAddress string `protobuf:"bytes,34,opt,name=shfu_grpc_address,json=shfuGrpcAddress,proto3" json:"shfu_grpc_address,omitempty"`
}

func (m *ProverConfig) Reset()         { *m = ProverConfig{} }
func (m *ProverConfig) String() string { return proto.CompactTextString(m) }
func (*ProverConfig) ProtoMessage()    {}
func (*ProverConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e6956e1b8ef896e, []int{0}
}
func (m *ProverConfig) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ProverConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ProverConfig.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ProverConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProverConfig.Merge(m, src)
}
func (m *ProverConfig) XXX_Size() int {
	return m.Size()
}
func (m *ProverConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ProverConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ProverConfig proto.InternalMessageInfo

type isProverConfig_ZkvmConfig interface {
	isProverConfig_ZkvmConfig()
	MarshalTo([]byte) (int, error)
	Size() int
}
type isProverConfig_OperatorsEip712Params interface {
	isProverConfig_OperatorsEip712Params()
	MarshalTo([]byte) (int, error)
	Size() int
}

type ProverConfig_Risc0ZkvmConfig struct {
	Risc0ZkvmConfig *Risc0ZKVMConfig `protobuf:"bytes,18,opt,name=risc0_zkvm_config,json=risc0ZkvmConfig,proto3,oneof" json:"risc0_zkvm_config,omitempty"`
}
type ProverConfig_OperatorsEip712EvmChainParams struct {
	OperatorsEip712EvmChainParams *EIP712EVMChainParams `protobuf:"bytes,31,opt,name=operators_eip712_evm_chain_params,json=operatorsEip712EvmChainParams,proto3,oneof" json:"operators_eip712_evm_chain_params,omitempty"`
}
type ProverConfig_OperatorsEip712CosmosChainParams struct {
	OperatorsEip712CosmosChainParams *EIP712CosmosChainParams `protobuf:"bytes,32,opt,name=operators_eip712_cosmos_chain_params,json=operatorsEip712CosmosChainParams,proto3,oneof" json:"operators_eip712_cosmos_chain_params,omitempty"`
}

func (*ProverConfig_Risc0ZkvmConfig) isProverConfig_ZkvmConfig()                             {}
func (*ProverConfig_OperatorsEip712EvmChainParams) isProverConfig_OperatorsEip712Params()    {}
func (*ProverConfig_OperatorsEip712CosmosChainParams) isProverConfig_OperatorsEip712Params() {}

func (m *ProverConfig) GetZkvmConfig() isProverConfig_ZkvmConfig {
	if m != nil {
		return m.ZkvmConfig
	}
	return nil
}
func (m *ProverConfig) GetOperatorsEip712Params() isProverConfig_OperatorsEip712Params {
	if m != nil {
		return m.OperatorsEip712Params
	}
	return nil
}

func (m *ProverConfig) GetRisc0ZkvmConfig() *Risc0ZKVMConfig {
	if x, ok := m.GetZkvmConfig().(*ProverConfig_Risc0ZkvmConfig); ok {
		return x.Risc0ZkvmConfig
	}
	return nil
}

func (m *ProverConfig) GetOperatorsEip712EvmChainParams() *EIP712EVMChainParams {
	if x, ok := m.GetOperatorsEip712Params().(*ProverConfig_OperatorsEip712EvmChainParams); ok {
		return x.OperatorsEip712EvmChainParams
	}
	return nil
}

func (m *ProverConfig) GetOperatorsEip712CosmosChainParams() *EIP712CosmosChainParams {
	if x, ok := m.GetOperatorsEip712Params().(*ProverConfig_OperatorsEip712CosmosChainParams); ok {
		return x.OperatorsEip712CosmosChainParams
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ProverConfig) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ProverConfig_Risc0ZkvmConfig)(nil),
		(*ProverConfig_OperatorsEip712EvmChainParams)(nil),
		(*ProverConfig_OperatorsEip712CosmosChainParams)(nil),
	}
}

type Fraction struct {
	Numerator   uint64 `protobuf:"varint,1,opt,name=numerator,proto3" json:"numerator,omitempty"`
	Denominator uint64 `protobuf:"varint,2,opt,name=denominator,proto3" json:"denominator,omitempty"`
}

func (m *Fraction) Reset()         { *m = Fraction{} }
func (m *Fraction) String() string { return proto.CompactTextString(m) }
func (*Fraction) ProtoMessage()    {}
func (*Fraction) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e6956e1b8ef896e, []int{1}
}
func (m *Fraction) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Fraction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Fraction.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Fraction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Fraction.Merge(m, src)
}
func (m *Fraction) XXX_Size() int {
	return m.Size()
}
func (m *Fraction) XXX_DiscardUnknown() {
	xxx_messageInfo_Fraction.DiscardUnknown(m)
}

var xxx_messageInfo_Fraction proto.InternalMessageInfo

type Risc0ZKVMConfig struct {
	ImageId string `protobuf:"bytes,1,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	Mock    bool   `protobuf:"varint,2,opt,name=mock,proto3" json:"mock,omitempty"`
}

func (m *Risc0ZKVMConfig) Reset()         { *m = Risc0ZKVMConfig{} }
func (m *Risc0ZKVMConfig) String() string { return proto.CompactTextString(m) }
func (*Risc0ZKVMConfig) ProtoMessage()    {}
func (*Risc0ZKVMConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e6956e1b8ef896e, []int{2}
}
func (m *Risc0ZKVMConfig) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Risc0ZKVMConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Risc0ZKVMConfig.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Risc0ZKVMConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Risc0ZKVMConfig.Merge(m, src)
}
func (m *Risc0ZKVMConfig) XXX_Size() int {
	return m.Size()
}
func (m *Risc0ZKVMConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_Risc0ZKVMConfig.DiscardUnknown(m)
}

var xxx_messageInfo_Risc0ZKVMConfig proto.InternalMessageInfo

type EIP712EVMChainParams struct {
	ChainId                  uint64 `protobuf:"varint,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	VerifyingContractAddress string `protobuf:"bytes,2,opt,name=verifying_contract_address,json=verifyingContractAddress,proto3" json:"verifying_contract_address,omitempty"`
}

func (m *EIP712EVMChainParams) Reset()         { *m = EIP712EVMChainParams{} }
func (m *EIP712EVMChainParams) String() string { return proto.CompactTextString(m) }
func (*EIP712EVMChainParams) ProtoMessage()    {}
func (*EIP712EVMChainParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e6956e1b8ef896e, []int{3}
}
func (m *EIP712EVMChainParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EIP712EVMChainParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EIP712EVMChainParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EIP712EVMChainParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EIP712EVMChainParams.Merge(m, src)
}
func (m *EIP712EVMChainParams) XXX_Size() int {
	return m.Size()
}
func (m *EIP712EVMChainParams) XXX_DiscardUnknown() {
	xxx_messageInfo_EIP712EVMChainParams.DiscardUnknown(m)
}

var xxx_messageInfo_EIP712EVMChainParams proto.InternalMessageInfo

type EIP712CosmosChainParams struct {
	ChainId string `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Prefix  string `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
}

func (m *EIP712CosmosChainParams) Reset()         { *m = EIP712CosmosChainParams{} }
func (m *EIP712CosmosChainParams) String() string { return proto.CompactTextString(m) }
func (*EIP712CosmosChainParams) ProtoMessage()    {}
func (*EIP712CosmosChainParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e6956e1b8ef896e, []int{4}
}
func (m *EIP712CosmosChainParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EIP712CosmosChainParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EIP712CosmosChainParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EIP712CosmosChainParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EIP712CosmosChainParams.Merge(m, src)
}
func (m *EIP712CosmosChainParams) XXX_Size() int {
	return m.Size()
}
func (m *EIP712CosmosChainParams) XXX_DiscardUnknown() {
	xxx_messageInfo_EIP712CosmosChainParams.DiscardUnknown(m)
}

var xxx_messageInfo_EIP712CosmosChainParams proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ProverConfig)(nil), "relayer.provers.lcp.config.ProverConfig")
	proto.RegisterType((*Fraction)(nil), "relayer.provers.lcp.config.Fraction")
	proto.RegisterType((*Risc0ZKVMConfig)(nil), "relayer.provers.lcp.config.Risc0ZKVMConfig")
	proto.RegisterType((*EIP712EVMChainParams)(nil), "relayer.provers.lcp.config.EIP712EVMChainParams")
	proto.RegisterType((*EIP712CosmosChainParams)(nil), "relayer.provers.lcp.config.EIP712CosmosChainParams")
}

func init() {
	proto.RegisterFile("relayer/provers/lcp/config/config.proto", fileDescriptor_2e6956e1b8ef896e)
}

var fileDescriptor_2e6956e1b8ef896e = []byte{
	// 1013 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x55, 0xcf, 0x6f, 0x1b, 0x45,
	0x14, 0xf6, 0xb6, 0x26, 0x89, 0xc7, 0x71, 0xd2, 0x4c, 0x42, 0xba, 0x49, 0x8b, 0xeb, 0x5a, 0x41,
	0x58, 0x20, 0xd6, 0x69, 0x82, 0x14, 0x21, 0x81, 0x44, 0xec, 0xb8, 0x6d, 0x0a, 0x45, 0x61, 0x13,
	0x2a, 0x11, 0x0e, 0xc3, 0x78, 0x76, 0xbc, 0x1e, 0x79, 0x77, 0x67, 0x99, 0xd9, 0x35, 0x71, 0xc4,
	0x95, 0x3b, 0x7f, 0x11, 0xe7, 0x1c, 0x7b, 0xe4, 0x84, 0x20, 0xf9, 0x47, 0xd0, 0xbc, 0x5d, 0xdb,
	0x69, 0x7e, 0xf5, 0x64, 0xcf, 0xfb, 0xbe, 0xf7, 0xcd, 0x9b, 0xf7, 0x6b, 0xd1, 0x27, 0x8a, 0x07,
	0x74, 0xc4, 0x55, 0x33, 0x56, 0x72, 0xc8, 0x95, 0x6e, 0x06, 0x2c, 0x6e, 0x32, 0x19, 0xf5, 0x84,
	0x9f, 0xff, 0x38, 0xb1, 0x92, 0x89, 0xc4, 0xeb, 0x39, 0xd1, 0xc9, 0x89, 0x4e, 0xc0, 0x62, 0x27,
	0x63, 0xac, 0xaf, 0xf8, 0xd2, 0x97, 0x40, 0x6b, 0x9a, 0x7f, 0x99, 0xc7, 0xfa, 0x9a, 0x2f, 0xa5,
	0x1f, 0xf0, 0x26, 0x9c, 0xba, 0x69, 0xaf, 0x49, 0xa3, 0x51, 0x06, 0xd5, 0xff, 0x2a, 0xa3, 0xf9,
	0x03, 0xd0, 0x69, 0x83, 0x02, 0xfe, 0x12, 0x55, 0xa4, 0x12, 0xbe, 0x88, 0x48, 0x26, 0x6f, 0x5b,
	0x35, 0xab, 0x51, 0xde, 0x5a, 0x71, 0x32, 0x0d, 0x67, 0xac, 0xe1, 0xec, 0x46, 0x23, 0x77, 0x3e,
	0xa3, 0x66, 0x02, 0xd8, 0x41, 0xcb, 0x01, 0x8b, 0x89, 0xe6, 0x6a, 0x28, 0x18, 0x27, 0xd4, 0xf3,
	0x14, 0xd7, 0xda, 0xbe, 0x57, 0xb3, 0x1a, 0x25, 0x77, 0x29, 0x60, 0xf1, 0x61, 0x86, 0xec, 0x66,
	0x00, 0xde, 0x41, 0xf6, 0x65, 0xbe, 0x27, 0x68, 0x40, 0x12, 0x11, 0x72, 0x99, 0x26, 0xf6, 0xfd,
	0x9a, 0xd5, 0x28, 0xba, 0x1f, 0x4e, 0x9d, 0xf6, 0x04, 0x0d, 0x8e, 0x32, 0x10, 0x3f, 0x46, 0xa5,
	0x50, 0xf1, 0x88, 0x05, 0x74, 0xc8, 0xed, 0x22, 0xc8, 0x4f, 0x0d, 0xf8, 0x0b, 0xb4, 0x4a, 0x83,
	0x40, 0xfe, 0xc6, 0x3d, 0xf2, 0x6b, 0x2a, 0x13, 0x4e, 0x74, 0x42, 0x93, 0x54, 0x73, 0x6d, 0x7f,
	0x50, 0xbb, 0xdf, 0x28, 0xb9, 0x2b, 0x39, 0xfa, 0x83, 0x01, 0x0f, 0x73, 0x0c, 0x6f, 0xa2, 0xb1,
	0x9d, 0x50, 0x6f, 0x28, 0xb4, 0x54, 0x23, 0x22, 0x3c, 0x6d, 0xcf, 0x80, 0x0f, 0xce, 0xb1, 0xdd,
	0x1c, 0xda, 0xf7, 0x34, 0xfe, 0x18, 0x2d, 0x0c, 0xf8, 0x88, 0xf0, 0x93, 0x58, 0x28, 0x9a, 0x08,
	0x19, 0xd9, 0xb3, 0x10, 0x74, 0x65, 0xc0, 0x47, 0x9d, 0x89, 0x11, 0x6f, 0xa3, 0x55, 0x43, 0x4b,
	0x63, 0x8f, 0x26, 0x9c, 0x74, 0xd3, 0x5e, 0x8f, 0x2b, 0x78, 0xa6, 0x3d, 0x07, 0xf4, 0xe5, 0x01,
	0x1f, 0xfd, 0x08, 0x60, 0x0b, 0x30, 0xf3, 0x48, 0x5c, 0x47, 0x15, 0x1e, 0x30, 0xc2, 0x02, 0xc1,
	0xa3, 0x84, 0x08, 0xcf, 0x2e, 0xc1, 0x2b, 0xcb, 0x3c, 0x60, 0x6d, 0xb0, 0xed, 0x7b, 0xb8, 0x89,
	0x96, 0x43, 0xae, 0x35, 0xf5, 0x39, 0xa1, 0xbe, 0xaf, 0xb8, 0x9f, 0x05, 0x81, 0x6a, 0x56, 0x63,
	0xce, 0xc5, 0x39, 0xb4, 0x3b, 0x45, 0x70, 0x1b, 0x55, 0x6f, 0x70, 0x20, 0x5d, 0x9a, 0xb0, 0x3e,
	0xd1, 0xe2, 0x94, 0xdb, 0x65, 0x88, 0xe8, 0xd1, 0x75, 0xdf, 0x96, 0xe1, 0x1c, 0x8a, 0x53, 0x8e,
	0x1b, 0xe8, 0x81, 0xd0, 0xc4, 0xe3, 0xdd, 0xd4, 0x27, 0xe3, 0x12, 0xcc, 0xc3, 0x95, 0x0b, 0x42,
	0xef, 0x19, 0x73, 0x27, 0xaf, 0xc3, 0x63, 0x54, 0x92, 0x31, 0x57, 0x34, 0x91, 0x4a, 0xdb, 0x15,
	0x48, 0xe3, 0xd4, 0x80, 0x7f, 0x46, 0xcb, 0x93, 0x03, 0x49, 0xfa, 0x8a, 0xeb, 0xbe, 0x0c, 0x3c,
	0x7b, 0x01, 0xba, 0x6d, 0xc3, 0xb9, 0xbd, 0xc7, 0x9d, 0xe7, 0x8a, 0x32, 0x88, 0xa9, 0x78, 0xf6,
	0xcf, 0x93, 0x82, 0x8b, 0x27, 0x32, 0x47, 0x63, 0x15, 0xfc, 0x35, 0x5a, 0x1c, 0x5b, 0x89, 0x16,
	0x7e, 0xc4, 0x95, 0xbd, 0x78, 0x47, 0x1b, 0x2f, 0x8c, 0xc9, 0x87, 0xc0, 0xc5, 0xaf, 0x50, 0x9d,
	0xa5, 0x4a, 0x99, 0xd4, 0x27, 0xac, 0x4b, 0xf8, 0x90, 0x06, 0x69, 0x96, 0x2b, 0x8f, 0x26, 0x94,
	0x44, 0x69, 0xd8, 0xe5, 0xca, 0x7e, 0x50, 0xb3, 0x1a, 0x15, 0xb7, 0x9a, 0x33, 0x8f, 0x58, 0xb7,
	0x33, 0xe1, 0xed, 0xd1, 0x84, 0x7e, 0x0f, 0x2c, 0xfc, 0x0b, 0x72, 0x6e, 0xd7, 0x18, 0x77, 0x85,
	0xaf, 0x28, 0xe3, 0x24, 0xe6, 0x4a, 0x48, 0xcf, 0x5e, 0x02, 0xdd, 0x46, 0x72, 0xb3, 0x60, 0xd6,
	0x2a, 0x2f, 0x8c, 0xc3, 0x01, 0xf0, 0xf1, 0x4f, 0x68, 0x49, 0x09, 0xcd, 0x36, 0xc9, 0xe9, 0x60,
	0x18, 0x92, 0x2c, 0x49, 0x36, 0x86, 0xe7, 0x7e, 0x76, 0x57, 0x1e, 0x5d, 0xe3, 0x74, 0xfc, 0xed,
	0x9b, 0xd7, 0xd9, 0xe4, 0xbf, 0x2c, 0xb8, 0x8b, 0xa0, 0x73, 0x3c, 0x18, 0x86, 0xf9, 0x32, 0xf8,
	0x1d, 0x3d, 0x9d, 0x16, 0x89, 0x8b, 0x78, 0xe7, 0xd9, 0x16, 0xe1, 0xe6, 0x92, 0x3e, 0x35, 0x0b,
	0x82, 0x2a, 0x1a, 0x6a, 0xfb, 0x09, 0x5c, 0xb5, 0x79, 0xd7, 0x55, 0x9d, 0xfd, 0x83, 0x9d, 0x67,
	0x5b, 0x9d, 0x37, 0xaf, 0xdb, 0xc6, 0xf1, 0x00, 0xfc, 0x5e, 0x5a, 0xee, 0x47, 0x13, 0xf1, 0x0e,
	0x68, 0x77, 0x86, 0xe1, 0x25, 0x02, 0xfe, 0xc3, 0x42, 0x1b, 0xd7, 0xae, 0x67, 0x52, 0x87, 0x52,
	0xbf, 0x1b, 0x41, 0x0d, 0x22, 0xd8, 0x7e, 0x7f, 0x04, 0x6d, 0x70, 0x7e, 0x37, 0x88, 0xda, 0x95,
	0x20, 0xae, 0x71, 0x70, 0x07, 0xd5, 0x42, 0x7a, 0x42, 0x58, 0x3f, 0x8d, 0x06, 0x30, 0x27, 0xa4,
	0x27, 0x27, 0xa5, 0xcb, 0x46, 0xd4, 0x7e, 0x0a, 0x45, 0x7b, 0x14, 0xd2, 0x93, 0xb6, 0xa1, 0x99,
	0x51, 0x79, 0x2e, 0xf3, 0x62, 0x65, 0x13, 0x8b, 0x3f, 0x45, 0x4b, 0xba, 0xdf, 0x4b, 0x89, 0xaf,
	0x62, 0x36, 0x59, 0x8e, 0x75, 0x98, 0xeb, 0x45, 0x03, 0xbc, 0x50, 0x31, 0xcb, 0x57, 0x63, 0xab,
	0x82, 0xca, 0x97, 0xaa, 0xd9, 0x5a, 0x43, 0x0f, 0xaf, 0x25, 0x22, 0x7b, 0x7b, 0xfd, 0x15, 0x9a,
	0x1b, 0x0f, 0x84, 0x99, 0xb8, 0x28, 0x0d, 0x33, 0x1e, 0xec, 0xed, 0xa2, 0x3b, 0x35, 0xe0, 0x1a,
	0x2a, 0x7b, 0x3c, 0x92, 0xa1, 0x88, 0x00, 0xbf, 0x07, 0xf8, 0x65, 0x53, 0xfd, 0x1b, 0xb4, 0x78,
	0xa5, 0x29, 0xf0, 0x1a, 0x9a, 0x13, 0xa1, 0xd9, 0x18, 0xc2, 0x03, 0xc5, 0x92, 0x3b, 0x0b, 0xe7,
	0x7d, 0x0f, 0x63, 0x54, 0x0c, 0x25, 0x1b, 0x80, 0xd0, 0x9c, 0x0b, 0xff, 0xeb, 0x12, 0xad, 0xdc,
	0x54, 0x6b, 0x23, 0x93, 0x55, 0x2c, 0x97, 0x29, 0xba, 0xb3, 0x70, 0xde, 0xf7, 0xf0, 0x57, 0x68,
	0x7d, 0xc8, 0x95, 0xe8, 0x8d, 0x44, 0xe4, 0x9b, 0xf7, 0x26, 0xe6, 0x35, 0x57, 0x3e, 0x1e, 0xf6,
	0x84, 0xd1, 0xce, 0x09, 0x79, 0xa2, 0xea, 0xdf, 0xa1, 0x87, 0xb7, 0x94, 0xf6, 0xda, 0x9d, 0xa5,
	0xe9, 0x9d, 0xab, 0x68, 0x26, 0x56, 0xbc, 0x27, 0x4e, 0x72, 0xfd, 0xfc, 0xd4, 0x6a, 0x9d, 0xfd,
	0x57, 0x2d, 0x9c, 0x9d, 0x57, 0xad, 0xb7, 0xe7, 0x55, 0xeb, 0xdf, 0xf3, 0xaa, 0xf5, 0xe7, 0x45,
	0xb5, 0xf0, 0xf6, 0xa2, 0x5a, 0xf8, 0xfb, 0xa2, 0x5a, 0x38, 0xde, 0xf0, 0x45, 0xd2, 0x4f, 0xbb,
	0x0e, 0x93, 0x61, 0xd3, 0x0c, 0x31, 0xa8, 0x05, 0xb4, 0x6b, 0xbe, 0xd4, 0x9f, 0xfb, 0xb2, 0x09,
	0xed, 0xd7, 0x9d, 0x81, 0xd5, 0xb2, 0xfd, 0x7f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x49, 0xad, 0xa6,
	0x4d, 0xd0, 0x07, 0x00, 0x00,
}

func (m *ProverConfig) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ProverConfig) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ProverConfig) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ShfuGrpcAddress) > 0 {
		i -= len(m.ShfuGrpcAddress)
		copy(dAtA[i:], m.ShfuGrpcAddress)
		i = encodeVarintConfig(dAtA, i, uint64(len(m.ShfuGrpcAddress)))
		i--
		dAtA[i] = 0x2
		i--
		dAtA[i] = 0x92
	}
	if m.MaxChunkSizeForUpdateClient != 0 {
		i = encodeVarintConfig(dAtA, i, uint64(m.MaxChunkSizeForUpdateClient))
		i--
		dAtA[i] = 0x2
		i--
		dAtA[i] = 0x88
	}
	if m.OperatorsEip712Params != nil {
		{
			size := m.OperatorsEip712Params.Size()
			i -= size
			if _, err := m.OperatorsEip712Params.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	if m.ZkvmConfig != nil {
		{
			size := m.ZkvmConfig.Size()
			i -= size
			if _, err := m.ZkvmConfig.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	if m.TcbEvaluationDataNumberUpdateGracePeriod != 0 {
		i = encodeVarintConfig(dAtA, i, uint64(m.TcbEvaluationDataNumberUpdateGracePeriod))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x88
	}
	if m.CurrentTcbEvaluationDataNumber != 0 {
		i = encodeVarintConfig(dAtA, i, uint64(m.CurrentTcbEvaluationDataNumber))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x80
	}
	if m.OperatorSigner != nil {
		{
			size, err := m.OperatorSigner.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintConfig(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x7a
	}
	{
		size, err := m.OperatorsThreshold.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintConfig(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x72
	if len(m.Operators) > 0 {
		for iNdEx := len(m.Operators) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Operators[iNdEx])
			copy(dAtA[i:], m.Operators[iNdEx])
			i = encodeVarintConfig(dAtA, i, uint64(len(m.Operators[iNdEx])))
			i--
			dAtA[i] = 0x6a
		}
	}
	if m.IsDebugEnclave {
		i--
		if m.IsDebugEnclave {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x60
	}
	if m.MessageAggregationBatchSize != 0 {
		i = encodeVarintConfig(dAtA, i, uint64(m.MessageAggregationBatchSize))
		i--
		dAtA[i] = 0x58
	}
	if m.MessageAggregation {
		i--
		if m.MessageAggregation {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x50
	}
	if len(m.ElcClientId) > 0 {
		i -= len(m.ElcClientId)
		copy(dAtA[i:], m.ElcClientId)
		i = encodeVarintConfig(dAtA, i, uint64(len(m.ElcClientId)))
		i--
		dAtA[i] = 0x4a
	}
	if m.KeyUpdateBufferTime != 0 {
		i = encodeVarintConfig(dAtA, i, uint64(m.KeyUpdateBufferTime))
		i--
		dAtA[i] = 0x40
	}
	if m.KeyExpiration != 0 {
		i = encodeVarintConfig(dAtA, i, uint64(m.KeyExpiration))
		i--
		dAtA[i] = 0x38
	}
	if len(m.AllowedAdvisoryIds) > 0 {
		for iNdEx := len(m.AllowedAdvisoryIds) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.AllowedAdvisoryIds[iNdEx])
			copy(dAtA[i:], m.AllowedAdvisoryIds[iNdEx])
			i = encodeVarintConfig(dAtA, i, uint64(len(m.AllowedAdvisoryIds[iNdEx])))
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.AllowedQuoteStatuses) > 0 {
		for iNdEx := len(m.AllowedQuoteStatuses) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.AllowedQuoteStatuses[iNdEx])
			copy(dAtA[i:], m.AllowedQuoteStatuses[iNdEx])
			i = encodeVarintConfig(dAtA, i, uint64(len(m.AllowedQuoteStatuses[iNdEx])))
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.Mrenclave) > 0 {
		i -= len(m.Mrenclave)
		copy(dAtA[i:], m.Mrenclave)
		i = encodeVarintConfig(dAtA, i, uint64(len(m.Mrenclave)))
		i--
		dAtA[i] = 0x22
	}
	if m.LcpServiceDialTimeout != 0 {
		i = encodeVarintConfig(dAtA, i, uint64(m.LcpServiceDialTimeout))
		i--
		dAtA[i] = 0x18
	}
	if len(m.LcpServiceAddress) > 0 {
		i -= len(m.LcpServiceAddress)
		copy(dAtA[i:], m.LcpServiceAddress)
		i = encodeVarintConfig(dAtA, i, uint64(len(m.LcpServiceAddress)))
		i--
		dAtA[i] = 0x12
	}
	if m.OriginProver != nil {
		{
			size, err := m.OriginProver.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintConfig(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ProverConfig_Risc0ZkvmConfig) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ProverConfig_Risc0ZkvmConfig) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.Risc0ZkvmConfig != nil {
		{
			size, err := m.Risc0ZkvmConfig.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintConfig(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x92
	}
	return len(dAtA) - i, nil
}
func (m *ProverConfig_OperatorsEip712EvmChainParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ProverConfig_OperatorsEip712EvmChainParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.OperatorsEip712EvmChainParams != nil {
		{
			size, err := m.OperatorsEip712EvmChainParams.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintConfig(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xfa
	}
	return len(dAtA) - i, nil
}
func (m *ProverConfig_OperatorsEip712CosmosChainParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ProverConfig_OperatorsEip712CosmosChainParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.OperatorsEip712CosmosChainParams != nil {
		{
			size, err := m.OperatorsEip712CosmosChainParams.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintConfig(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2
		i--
		dAtA[i] = 0x82
	}
	return len(dAtA) - i, nil
}
func (m *Fraction) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Fraction) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Fraction) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Denominator != 0 {
		i = encodeVarintConfig(dAtA, i, uint64(m.Denominator))
		i--
		dAtA[i] = 0x10
	}
	if m.Numerator != 0 {
		i = encodeVarintConfig(dAtA, i, uint64(m.Numerator))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Risc0ZKVMConfig) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Risc0ZKVMConfig) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Risc0ZKVMConfig) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Mock {
		i--
		if m.Mock {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	if len(m.ImageId) > 0 {
		i -= len(m.ImageId)
		copy(dAtA[i:], m.ImageId)
		i = encodeVarintConfig(dAtA, i, uint64(len(m.ImageId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EIP712EVMChainParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EIP712EVMChainParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EIP712EVMChainParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.VerifyingContractAddress) > 0 {
		i -= len(m.VerifyingContractAddress)
		copy(dAtA[i:], m.VerifyingContractAddress)
		i = encodeVarintConfig(dAtA, i, uint64(len(m.VerifyingContractAddress)))
		i--
		dAtA[i] = 0x12
	}
	if m.ChainId != 0 {
		i = encodeVarintConfig(dAtA, i, uint64(m.ChainId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *EIP712CosmosChainParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EIP712CosmosChainParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EIP712CosmosChainParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Prefix) > 0 {
		i -= len(m.Prefix)
		copy(dAtA[i:], m.Prefix)
		i = encodeVarintConfig(dAtA, i, uint64(len(m.Prefix)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ChainId) > 0 {
		i -= len(m.ChainId)
		copy(dAtA[i:], m.ChainId)
		i = encodeVarintConfig(dAtA, i, uint64(len(m.ChainId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintConfig(dAtA []byte, offset int, v uint64) int {
	offset -= sovConfig(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ProverConfig) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.OriginProver != nil {
		l = m.OriginProver.Size()
		n += 1 + l + sovConfig(uint64(l))
	}
	l = len(m.LcpServiceAddress)
	if l > 0 {
		n += 1 + l + sovConfig(uint64(l))
	}
	if m.LcpServiceDialTimeout != 0 {
		n += 1 + sovConfig(uint64(m.LcpServiceDialTimeout))
	}
	l = len(m.Mrenclave)
	if l > 0 {
		n += 1 + l + sovConfig(uint64(l))
	}
	if len(m.AllowedQuoteStatuses) > 0 {
		for _, s := range m.AllowedQuoteStatuses {
			l = len(s)
			n += 1 + l + sovConfig(uint64(l))
		}
	}
	if len(m.AllowedAdvisoryIds) > 0 {
		for _, s := range m.AllowedAdvisoryIds {
			l = len(s)
			n += 1 + l + sovConfig(uint64(l))
		}
	}
	if m.KeyExpiration != 0 {
		n += 1 + sovConfig(uint64(m.KeyExpiration))
	}
	if m.KeyUpdateBufferTime != 0 {
		n += 1 + sovConfig(uint64(m.KeyUpdateBufferTime))
	}
	l = len(m.ElcClientId)
	if l > 0 {
		n += 1 + l + sovConfig(uint64(l))
	}
	if m.MessageAggregation {
		n += 2
	}
	if m.MessageAggregationBatchSize != 0 {
		n += 1 + sovConfig(uint64(m.MessageAggregationBatchSize))
	}
	if m.IsDebugEnclave {
		n += 2
	}
	if len(m.Operators) > 0 {
		for _, s := range m.Operators {
			l = len(s)
			n += 1 + l + sovConfig(uint64(l))
		}
	}
	l = m.OperatorsThreshold.Size()
	n += 1 + l + sovConfig(uint64(l))
	if m.OperatorSigner != nil {
		l = m.OperatorSigner.Size()
		n += 1 + l + sovConfig(uint64(l))
	}
	if m.CurrentTcbEvaluationDataNumber != 0 {
		n += 2 + sovConfig(uint64(m.CurrentTcbEvaluationDataNumber))
	}
	if m.TcbEvaluationDataNumberUpdateGracePeriod != 0 {
		n += 2 + sovConfig(uint64(m.TcbEvaluationDataNumberUpdateGracePeriod))
	}
	if m.ZkvmConfig != nil {
		n += m.ZkvmConfig.Size()
	}
	if m.OperatorsEip712Params != nil {
		n += m.OperatorsEip712Params.Size()
	}
	if m.MaxChunkSizeForUpdateClient != 0 {
		n += 2 + sovConfig(uint64(m.MaxChunkSizeForUpdateClient))
	}
	l = len(m.ShfuGrpcAddress)
	if l > 0 {
		n += 2 + l + sovConfig(uint64(l))
	}
	return n
}

func (m *ProverConfig_Risc0ZkvmConfig) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Risc0ZkvmConfig != nil {
		l = m.Risc0ZkvmConfig.Size()
		n += 2 + l + sovConfig(uint64(l))
	}
	return n
}
func (m *ProverConfig_OperatorsEip712EvmChainParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.OperatorsEip712EvmChainParams != nil {
		l = m.OperatorsEip712EvmChainParams.Size()
		n += 2 + l + sovConfig(uint64(l))
	}
	return n
}
func (m *ProverConfig_OperatorsEip712CosmosChainParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.OperatorsEip712CosmosChainParams != nil {
		l = m.OperatorsEip712CosmosChainParams.Size()
		n += 2 + l + sovConfig(uint64(l))
	}
	return n
}
func (m *Fraction) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Numerator != 0 {
		n += 1 + sovConfig(uint64(m.Numerator))
	}
	if m.Denominator != 0 {
		n += 1 + sovConfig(uint64(m.Denominator))
	}
	return n
}

func (m *Risc0ZKVMConfig) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ImageId)
	if l > 0 {
		n += 1 + l + sovConfig(uint64(l))
	}
	if m.Mock {
		n += 2
	}
	return n
}

func (m *EIP712EVMChainParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ChainId != 0 {
		n += 1 + sovConfig(uint64(m.ChainId))
	}
	l = len(m.VerifyingContractAddress)
	if l > 0 {
		n += 1 + l + sovConfig(uint64(l))
	}
	return n
}

func (m *EIP712CosmosChainParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ChainId)
	if l > 0 {
		n += 1 + l + sovConfig(uint64(l))
	}
	l = len(m.Prefix)
	if l > 0 {
		n += 1 + l + sovConfig(uint64(l))
	}
	return n
}

func sovConfig(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozConfig(x uint64) (n int) {
	return sovConfig(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ProverConfig) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowConfig
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ProverConfig: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ProverConfig: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OriginProver", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthConfig
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.OriginProver == nil {
				m.OriginProver = &types.Any{}
			}
			if err := m.OriginProver.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LcpServiceAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConfig
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LcpServiceAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LcpServiceDialTimeout", wireType)
			}
			m.LcpServiceDialTimeout = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LcpServiceDialTimeout |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Mrenclave", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConfig
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Mrenclave = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AllowedQuoteStatuses", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConfig
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AllowedQuoteStatuses = append(m.AllowedQuoteStatuses, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AllowedAdvisoryIds", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConfig
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AllowedAdvisoryIds = append(m.AllowedAdvisoryIds, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field KeyExpiration", wireType)
			}
			m.KeyExpiration = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.KeyExpiration |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field KeyUpdateBufferTime", wireType)
			}
			m.KeyUpdateBufferTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.KeyUpdateBufferTime |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ElcClientId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConfig
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ElcClientId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MessageAggregation", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.MessageAggregation = bool(v != 0)
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MessageAggregationBatchSize", wireType)
			}
			m.MessageAggregationBatchSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MessageAggregationBatchSize |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsDebugEnclave", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsDebugEnclave = bool(v != 0)
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Operators", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConfig
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Operators = append(m.Operators, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OperatorsThreshold", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthConfig
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.OperatorsThreshold.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 15:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OperatorSigner", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthConfig
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.OperatorSigner == nil {
				m.OperatorSigner = &types.Any{}
			}
			if err := m.OperatorSigner.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 16:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurrentTcbEvaluationDataNumber", wireType)
			}
			m.CurrentTcbEvaluationDataNumber = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CurrentTcbEvaluationDataNumber |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 17:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TcbEvaluationDataNumberUpdateGracePeriod", wireType)
			}
			m.TcbEvaluationDataNumberUpdateGracePeriod = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TcbEvaluationDataNumberUpdateGracePeriod |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 18:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Risc0ZkvmConfig", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthConfig
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &Risc0ZKVMConfig{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.ZkvmConfig = &ProverConfig_Risc0ZkvmConfig{v}
			iNdEx = postIndex
		case 31:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OperatorsEip712EvmChainParams", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthConfig
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &EIP712EVMChainParams{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.OperatorsEip712Params = &ProverConfig_OperatorsEip712EvmChainParams{v}
			iNdEx = postIndex
		case 32:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OperatorsEip712CosmosChainParams", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthConfig
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &EIP712CosmosChainParams{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.OperatorsEip712Params = &ProverConfig_OperatorsEip712CosmosChainParams{v}
			iNdEx = postIndex
		case 33:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxChunkSizeForUpdateClient", wireType)
			}
			m.MaxChunkSizeForUpdateClient = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxChunkSizeForUpdateClient |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 34:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ShfuGrpcAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConfig
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ShfuGrpcAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipConfig(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthConfig
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Fraction) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowConfig
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Fraction: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Fraction: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Numerator", wireType)
			}
			m.Numerator = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Numerator |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denominator", wireType)
			}
			m.Denominator = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Denominator |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipConfig(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthConfig
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Risc0ZKVMConfig) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowConfig
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Risc0ZKVMConfig: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Risc0ZKVMConfig: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ImageId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConfig
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ImageId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Mock", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Mock = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipConfig(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthConfig
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EIP712EVMChainParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowConfig
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EIP712EVMChainParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EIP712EVMChainParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainId", wireType)
			}
			m.ChainId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ChainId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VerifyingContractAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConfig
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VerifyingContractAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipConfig(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthConfig
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EIP712CosmosChainParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowConfig
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EIP712CosmosChainParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EIP712CosmosChainParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConfig
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChainId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Prefix", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConfig
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Prefix = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipConfig(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthConfig
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipConfig(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowConfig
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthConfig
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupConfig
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthConfig
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthConfig        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowConfig          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupConfig = fmt.Errorf("proto: unexpected end of group")
)
