name: test
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  e2e-test:
    runs-on:
      labels: ubuntu-22.04-16core
    env:
      SGX_MODE: SW
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - uses: dtolnay/rust-toolchain@nightly
      - uses: datachainlab/rust-cache@allow_registry_src_caching
        with:
          workspaces: |
            ./lcp
            ./lcp/enclave
          cache-directories: |
            ~/.cargo/registry/src/**/librocksdb-sys-*
      - run: sudo bash ./lcp/.github/scripts/install_sgx_sdk.sh /opt
      - run: make tendermint-images
      - run: source /opt/sgxsdk/environment && make e2e-test
      - run: source /opt/sgxsdk/environment && make E2E_OPTIONS="--operators_enabled" e2e-test
      - run: source /opt/sgxsdk/environment && make E2E_OPTIONS="--zkdcap --operators_enabled" e2e-test
